name: Deploy to FTP

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 45.137.159.69
          username: u392776179.umeshahewage
          password: Aruna@umesha123
          server-dir: './'
          local-dir: './'
